[package]
name = "RustPong"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]

[dependencies.log]
version = "0.4.14"

[dependencies]
rand = "0.7.3"